module.exports.home = require('./home')
module.exports.auth = require('./auth')
module.exports.profiles = require('./profiles')
module.exports.tweets = require('./tweets')
module.exports.brands = require('./brands')
